[package]
name = "multilayer_perceptron"
version = "0.1.0"
authors = ["Simon Galasso <simon.galasso@hotmail.fr>"]
edition = "2018"

[lib]
path = "src/main.rs"

[dependencies]
rand = "0.7.3"
rulinalg = "0.4.2"
